# The Site Configuration

theme: jekyll-theme-chirpy
lang: en
title: RedpingDev Blog # the main title
tagline: A text-focused Jekyll theme # it will display as the subtitle
description: 'Redping Dev Blog'
baseurl: ""
url: https://RedpingDev.github.io
# The base URL of your site

github:
  username: RedpingDev # change to your GitHub username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Redping
  email: redping32@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/RedpingDev # change to your GitHub homepage
    - https://linktr.ee/RedpingGames
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username


# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID


# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: dark

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /img/avatar.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: giscus
  giscus:
    repo: "RedpingDev/RedpingDev.github.io"
    repo_id: "R_kgDONJVX7Q"
    category: "Show and tell"
    category_id: "DIC_kwDONJVX7c4Cj6pm"
    mapping: "pathname"
    strict: 0
    input_position: "bottom"
    lang: "ko"
    reactions_enabled: 1

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10


# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package.json


jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-seo-tag
  # - jekyll-polyglot
  - jekyll-sitemap

# languages: ["en", "ko"]
# default_lang: 'ko'
# exclude_from_localization: ["assets", "css", "images", "javascript"]
# parallel_localization: false

webmaster_verifications:
  google: QULqxl9mbPCaSWd7zX5n0sy9S8dT9F0Y8zPmUffIZbY

